### ISSUE TITLE
MIT license for code

### ISSUE THREAD

**Issue by dpsanders** [JuliaComputing/JuliaAcademyMaterials#18]
A CC license makes sense for the textual material, but not (I believe) for code, which should have an open-source license like MIT.

**Comment by ericphanson** [comment]
I would also like to request a MIT license-- I'd like to reuse the `build.jl` file for a similar setup for Convex.jl's examples (JuliaOpt/Convex.jl#335), but I'm a bit concerned about the license.

**Comment by ViralBShah** [comment]
Fixed in e299de4a9270badf710bdef96e47491d832acf9e
