### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by HamletFr** [JuliaComputing/JuliaAcademyMaterials#20]
With following your build suggestions in Julia 1.2.0 I get the following error:

```
Activating environment at `~/.Trash/JuliaAcademyMaterials/Notebooks/Deep learning with Flux/Project.toml`
ERROR: LoadError: Package TOML [9d418dce-91a8-11e8-0173-7b01a971d501] not found in a registry.
```

I thought, that TOML has moved to the Stdlib.

Any suggestions how to solve the problem?

Thanks in advance.

**Comment by logankilpatrick** [comment]
Yep, @mbauman the Manifest file has TOML which is not in the registry anymore.
