### ISSUE TITLE
Improvement for JuliaAcademy

### ISSUE THREAD

**Issue by Hry789** [JuliaComputing/JuliaAcademyMaterials#28]
This courses are just good, but the volume and the speed of the mentor could be adjustable, just to give more example, doing a live 1 to 1 teaching is a good option!
Anyway, it was really great.The mentor had already given a try and a good example to the beginners. Thanks a lot and I had learnt a lot from JuliaAcademy.
![Capture](https://user-images.githubusercontent.com/43082512/71558214-982b0b80-2a8b-11ea-8259-7f5d95e4e93c.PNG)
![Capture1](https://user-images.githubusercontent.com/43082512/71558215-98c3a200-2a8b-11ea-9035-c30fb9b8fcaf.PNG)

**Comment by logankilpatrick** [comment]
Hey! See this thread: https://github.com/JuliaComputing/JuliaAcademyMaterials/issues/23

**Comment by logankilpatrick** [comment]
You can close this issue and move your thoughts there. Also, maybe elaborate more on why the speed of the course/content was too fast? Do you mean the speed of the content? Or the actual words spoken by Jane?
