### ISSUE TITLE
Conclusion for JuliaAcademy

### ISSUE THREAD

**Issue by Hry789** [JuliaComputing/JuliaAcademyMaterials#31]
Anyway it quite a good course,just maybe the speed of the mentor could be more louder and subtittle may be added.As some people may not understand well,exercise or comment could be added.

The progress of participants can be evaluated during the course through their participation in workshops, practical exercises and the discussion sessions where each module would be discussed before proceeding to the next stage of the course. Depending on the length of the course and the specific objectives, a more exhaustive evaluation process could be initiated. This would be possible in the training courses extending over a week or just putting the course to various parts.

This course provided an introduction to studying Julia language. It took you through a series of video designed to develop your approach to study and learning at a distance, and helped to improve your confidence as an independent learner.

**Comment by logankilpatrick** [comment]
Hey Hry789, please move these comments over to https://github.com/JuliaComputing/JuliaAcademyMaterials/issues/22

**Comment by logankilpatrick** [comment]
Once you have done this, please close this issue. Thanks!
