### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by srikarthi1144** [JuliaComputing/JuliaAcademyMaterials#37]
Generally i loved to learn 😇  Julia it was interesting language but similar to python if you python it would be easier . coming to the tutorial video were small and audio quality was low there was only one question secession and it wasn't interactive . It's didn't have any codeing secession too

**Comment by logankilpatrick** [comment]
Hey @srikarthi1144, please move your comments to the appropriate thread linked in the Code-In Task.

**Comment by logankilpatrick** [comment]
Once that is done, please close this issue. Thanks!

**Comment by srikarthi1144** [comment]
Thanks for your reply and mentorship sir
