### ISSUE TITLE
Review of Intro to Julia Course

### ISSUE THREAD

**Issue by SPARTACUS5329** [JuliaComputing/JuliaAcademyMaterials#41]
The course is good(overall).  I(Aditya Kovilur) think:
1. Although it is just an introduction , there should be a mini-project in the end the instructor shows how to create to actually make the viewer understand how all the parts work together.
2. The course should include the rea
![Task3(Img)](https://user-images.githubusercontent.com/58896813/71715643-201c6700-2e38-11ea-909b-745c3cbff25a.jpg)Re
sons why Julia is better than other languages(if it is, because I think it is just a derivative of Python) and it's scopes .
3.There should be a lesson after the intro which gives examples how Julia can be integrated  with other languages to create  something extraordinary(like Python with R and SQL for Data Analysis)

**Comment by logankilpatrick** [comment]
Hey @SPARTACUS5329 thanks for the feedback! Please move this thread over to the appropriately linked thread in the Google Code-in task.
