### ISSUE TITLE
Thread to claim topics for added quiz material (Introduction to Julia Course)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#42]
Post the topic you will be making a quiz on here. Note that if another student claims the task, you should choose a different topic. The topics are as follows: 

- Control Flow
- Packages 
- Plotting
- Multiple Dispatch
- Basic Linear Algebra
- "Julia is fast" 

Note that these quizzes can only cover material that was found in the actual videos that are in the Introduction to Julia course on JuliaAcademy.org. 

Note the quiz can be less than 7-10 questions if the section doesn’t have enough content for that many questions.

**Comment by TheComputerM** [comment]
I am choosing the `Packages` topic.

**Comment by PseudoCodeNerd** [comment]
I haven't claimed the task yet but I'm gonna go with `Basic Linear Algebra` in Julia.

**Comment by soumitradev** [comment]
I haven't claimed the task, but I'll be working on `Control Flow`.

**Comment by josobar** [comment]
I will work on the `Plotting` section

**Comment by logankilpatrick** [comment]
Note that if another student claims the task and submits a quiz for the section you wanted before you claim the task, that students quiz will be accepted and you will have to find a different section. This is to prevent people from pre-collecting tasks and such. Thanks everyone!

**Comment by CompSciDZ** [comment]
I can work on "Julia is fast"

**Comment by CompSciDZ** [comment]
I will work on `"Julia is fast"`

**Comment by chinglamchoi** [comment]
Sure I'll work on `Multiple Dispatch`!

**Comment by soumitradev** [comment]
I’ll work on multiple dispatch since jo task was submitted for multiple dispatch. I have already claimed the task.
