### ISSUE TITLE
Good Courses :)

### ISSUE THREAD

**Issue by anshCoder** [JuliaComputing/JuliaAcademyMaterials#43]
The Courses are quite good
Explanation is  better than other Sites :)
I have learnt many New Concepts by it!

**Comment by logankilpatrick** [comment]
Hey @anshCoder Thanks for the feedback! This issue should be closed and you should move this thread over to the issue linked in the Google Code-in task. Also, please be sure to provide 2-3 specific pieces of feedback that we can use to improve the course. 

Keep up the great work!
