### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by sankalpdass** [JuliaComputing/JuliaAcademyMaterials#45]
*Feedback*
![PhotoEditor_20200105_122849529](https://user-images.githubusercontent.com/56037184/71783510-ae961180-300d-11ea-970c-d82eb9681718.jpg)

Actually the course on Julia academy are so interesting that I watched all videos of your forum including "introduction to julia" course.
Now I observed some pros and cons of your course i.e. "introduction to julia" and some details are mentioned below : -

Pros:-
• tutorial video of course teach about how to code with Julia language.

• content of topic description at starting of each video was very helpful.

• the concepts taught on the video was very helpful to solve basic problems.

Cons:- 

(The cons are noticable. You must apply these changes to make it more better.)

• The starting of course is not much interesting because the instructor do not tell the advantages to learn Julia language at starting of course but later on she described it but, as we all know first impression is the last impression so she must explain the advantage at the very beginning of course to make the course interactive for Julia learner.

• there is no video of installation of julia in IDE, how to get friendly with this Julia language and what else we can do with this in future.

• most important there are no minor projects covered in the video tutorial as we all know without project we can't understand any language.

• also the video are too short to understand because functions can't be understand in just 10 minutes.it takes time to understand function.

• The instructor of video teach very fast and skipped many concepts that must be taught to understand any language to learn coding. For example she didn't give many examples to understand loops at first time. 

[combinepdf.pdf](https://github.com/JuliaComputing/JuliaAcademyMaterials/files/4023714/combinepdf.pdf)

**Comment by logankilpatrick** [comment]
Hey @sankalpdass Please move this feedback to #23 and then close this issue! Thanks.

**Comment by sankalpdass** [comment]
I closed the previous issue.
