### ISSUE TITLE
Improvements to Machine Learning Course- By Shyam Vyas

### ISSUE THREAD

**Issue by shyamvyas890** [JuliaComputing/JuliaAcademyMaterials#48]
Hello, I hate to tell you, but this course was absolutely terrible. All the course did was show a guy using machine learning in his everyday life, but didn't show what goes on behind the scenes and how to code machine learning programs in Julia.

Also, all courses should have quizzes, homework, and tests to assess whether someone has actually understood what is being taught or not. This course just has a few youtube videos, which might as well be compiled into a YouTube playlist.

Furthermore, the man in the videos speaks extremely slowly, and I had to put it on 2* speed just to concentrate on what that guy was saying. The guys was also speaking extremely softly, so I had to greatly crank up my volume to hear even what he was saying. 

Also, for the latter videos, the person filmed had 3 walls and a closet right behind him (as opposed to just him) which gave an extremely unprofessional look to the audience. This could make people distrust the course and look for other courses to learn machine learning.

Also, I couldn't click the next video for it to count towards my progress, because if I did that, my progress would remain the same. I had to click "complete and continue" and then only would it count towards my progress. that was extremely weird, since someone could just watch none of the videos and just click next, next, next, and get 100% complete on their course.

So, overall, MANY improvements could be made to this course and I hope they are made!

**Comment by logankilpatrick** [comment]
Hey @shyamvyas890 please move this feedback to #25 and then close this issue. Thanks!
