### ISSUE TITLE
Thread to claim topics for added quiz material (Foundations of Machine Learning Course)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#50]
Post the topic you will be making a quiz on here. Note that if another student claims the task, you should choose a different topic. _Please do not claim a topic here unless you have claimed the task on the Code-in site_

Topics must be picked from the below list: 
-  Representing Data with Models
- Building Models
- Model Complexity
- What is Learning?
- What are Neurons?

Note that these quizzes can only cover material that was found in the actual videos that are in the Foundations of Machine Learning course on JuliaAcademy.org.

Note the quiz can be less than 7-10 questions if the section doesn’t have enough content for that many questions.

**Comment by TheComputerM** [comment]
I am claiming the topic `Building Models`.

**Comment by CompSciDZ** [comment]
I will make a quiz on `Representing Data with Models`

**Comment by fungktt** [comment]
I will be making one on "What is Learning?"

**Comment by harshitjethi** [comment]
I am claiming what is learning

**Comment by ishita272001** [comment]
I will be making what is neurons

**Comment by soumitradev** [comment]
I'll work on `Model Complexity`

**Comment by fungktt** [comment]
I will be making one on "What is Learning?"

**Comment by ishita272001** [comment]
I will be making on what is neurons

**Comment by chinglamchoi** [comment]
I'll work on what are neurons :)
