### ISSUE TITLE
Improvements to Machine Learning Course- By Shyam Vyas

### ISSUE THREAD

**Issue by shyamvyas890** [JuliaComputing/JuliaAcademyMaterials#51]
Hello, I hate to tell you, but this course was not the best course. Although I acknowledge the great efforts he put in, all the course did was show a guy using machine learning in his everyday life, but didn't show what goes on behind the scenes and how to code machine learning programs in Julia.

Also, all courses should have quizzes, homework, and tests to assess whether someone has actually understood what is being taught or not. This course just has a few youtube videos, which might as well be compiled into a YouTube playlist.

Furthermore, the man in the videos speaks extremely slowly, and I had to put it on 2* speed just to concentrate on what that guy was saying. The guys was also speaking extremely softly, so I had to greatly crank up my volume to hear even what he was saying.

Also, for the latter videos, the person filmed had 3 walls and a closet right behind him (as opposed to just him) which gave an extremely unprofessional look to the audience. This could make people distrust the course and look for other courses to learn machine learning.

Also, I couldn't click the next video for it to count towards my progress, because if I did that, my progress would remain the same. I had to click "complete and continue" and then only would it count towards my progress. that was extremely weird, since someone could just watch none of the videos and just click next, next, next, and get 100% complete on their course.

So, overall, MANY improvements could be made to this course and I hope they are made!

**Comment by ViralBShah** [comment]
@shyamvyas890 These comments are not constructive. Please frame your comments in a constructive way. The authors have spent a considerable amount of time preparing these videos.

I assume you are participating in Google Code-In, and you should know that comments of such nature that you make will be on the internet for a very long time, which may not reflect well as you progress in your career.

**Comment by shyamvyas890** [comment]
Yes, I completely understand, and am simply providing constructive feedback that I could think of for google code-in. If I just say the course was good, and don't point out flaws in it, I don't get approved. But, these are the genuine flaws in the program.

**Comment by ViralBShah** [comment]
Right - the idea was not to praise the course, but use the right language. Thank you for editing your original post. 

Which exact course are you referring to (because there are a few on ML)? 

In terms of next->next->next to finish the course, I don't think we want to police it. It is for self-learning (no grades, no certificates). But a lot of students have commented about quizzes and such in order to ensure they mastered the course.

**Comment by shyamvyas890** [comment]
The World of Machine learning With Knet
