### ISSUE TITLE
Thread to claim topics for added quiz material (Deep Learning with Flux.jl Course)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#52]
Post the topic you will be making a quiz on here. Note that if another student claims the task, you should choose a different topic. _Please do not claim a topic here unless you have claimed the task on the Code-in site_

Topics must be picked from the below list: 
- Introduction to Neural Networks
- Deep Learning with Flux
- Recongnizing handwriting with a neural network
- Final summary test consisting of questions for the entire course

Note that these quizzes can only cover material that was found in the actual videos that are in the Deep Learning with Flux.jl course on JuliaAcademy.org.

Note the quiz can be less than 7-10 questions if the section doesn’t have enough content for that many questions but for this section the videos are longer and should have plenty of content for a quiz.

**Comment by chinglamchoi** [comment]
I'll work on recognising handwriting with a neural network!

**Comment by CompSciDZ** [comment]
I can work on `Deep Learning with Flux`

**Comment by TheComputerM** [comment]
I am claiming `Introduction to Neural Networks`.

**Comment by mikolajhojda** [comment]
I'll work with final summary
