### ISSUE TITLE
Thread to claim topics for added quiz material (the World of Machine Learning with Knet Course)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#53]
Post the topic you will be making a quiz on here. Note that if another student claims the task, you should choose a different topic. Please do not claim a topic here unless you have claimed the task on the Code-in site

Topics must be picked from the below list:
- Visual Question and Answering 
- Handwriting Recognition in Julia
- Sentiment Analysis
- Language Modeling
- Image Classification
- A final summary test consisting of questions for the entire course

_Note that these quizzes can only cover material that was found in the actual videos that are in the World of Machine Learning with Knet on JuliaAcademy.org. _ Please do not reference or ask questions about outside material that the person taking the quiz may not know.

Note the quiz can be less than 7-10 questions if the section doesn’t have enough content for that many questions but for this section the videos are longer and should have plenty of content for a quiz.

**Comment by CompSciDZ** [comment]
I will do `Visual Question and Answering`

**Comment by chinglamchoi** [comment]
I will do the overall summary questions.
