### ISSUE TITLE
Thread to claim topics for added quiz material (Parallel Computing Course)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#62]
Post the topic you will be making a quiz on here. Note that if another student claims the task, you should choose a different topic. Please do not claim a topic here unless you have claimed the task on the Code-in site

Topics must be picked from the below list:
- Introduction
- Performance Overview 
- Serial Performance
- Single Instruction, Multiple Data
- Multithreading (2 quizzes for this section because it's long)
- Parallel Algorithm Design
- Tasks (Co-routines)
- Distributed computing (2 quizzes for this section because it's long)
- GPU's
- A final summary test consisting of questions for the entire course (should be 15-20 questions)
   *(2 instances for this) task ^ *

_Note that these quizzes can only cover material that was found in the actual videos that are in the Parallel Computing Course on JuliaAcademy.org. _ Please do not reference or ask questions about outside material that the person taking the quiz may not know.

Note the quiz can be less than 7-10 questions if the section doesn’t have enough content for that many questions but for this section the videos are longer and should have plenty of content for a quiz.

**Comment by chinglamchoi** [comment]
I'll take Performance Overview!

**Comment by CompSciDZ** [comment]
I can take `Introduction`

**Comment by Arpan612** [comment]
I will take GPUs
