### ISSUE TITLE
My feedback on this course.

### ISSUE THREAD

**Issue by D-Studios** [JuliaComputing/JuliaAcademyMaterials#63]
I enjoyed participating in this course but I did have a few issues with the videos.

Issues:
1) The audio sometimes in the videos was not clean. There was background noises that were pretty clear to hear and this was distracting.
2) I was not quizzed a lot through the whole course. This made it hard for me to retain details which I had just learned.
3) Finally, I believe either the course should state that there are prerequisites, or cover essential information that is needed to be known before enrollment. For the last two videos of this course, I thoroughly did not understand much due to the fact that I have not learned such complex mathematics yet.

**Comment by logankilpatrick** [comment]
Hey @D-Studios Please move this feedback to the thread linked in the GCI task. Thanks!
