### ISSUE TITLE
Feedback for potential improvements

### ISSUE THREAD

**Issue by amyhu0114** [JuliaComputing/JuliaAcademyMaterials#68]
The course is really helpful for beginners as it incorporates examples that are easy to understand. I enjoy learning the basics of machine learning through short videos.
Here are my suggestions for potential improvements:
  1) Maybe include some hands-on exercises where students could try out the concepts learned themselves
  2) Include some quizzes with multiple choice/short answer questions to ensure the students understand the concepts
The course is great overall! =)

**Comment by logankilpatrick** [comment]
Please move this to the thread linked in the GCI task!
